# Dependencies
highlighter:      rouge

# Permalinks
permalink:        /:categories/:slug/
# relative_permalinks: true

# Setup
title:            Pranta's Notes
tagline:          'Notes about this and that and softwares'
description:      ''
url:              https://Pranta-Saha.github.io
baseurl:          ''          

plugins:
  - jekyll-seo-tag
  - jekyll-feed

author:
  name:           'Pranta-Saha'
  url:            https://github.com/Pranta-Saha


# For a global message in the head
message: 
